version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: portfolio-postgres
    environment:
      POSTGRES_DB: portfolio_backtest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: portfolio-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password123
      DOCKER_INFLUXDB_INIT_ORG: portfolio-org
      DOCKER_INFLUXDB_INIT_BUCKET: market-data
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: portfolio-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # InfluxDB Web UI (可选)
  influxdb-ui:
    image: influxdb:2.7
    container_name: portfolio-influxdb-ui
    depends_on:
      - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - "8087:8086"
    profiles:
      - ui

volumes:
  postgres_data:
  influxdb_data:
  influxdb_config:
  redis_data: